### ISSUE TITLE
Wrong Weighted-Avg F1 in All Experiments

### ISSUE THREAD

**Issue by fpcsong** [whatissimondoing/CoG-BART#1]
Thanks your nice work for ERC,  a bug from TODKAT was not fixed in your code, see https://github.com/something678/TodKat/issues/10.
You may need fix it and report the new results.

Best regards.

**Comment by whatissimondoing** [comment]
Thank you for your feedback, we have fixed this bug and will report new results in the new version.

**Comment by whatissimondoing** [comment]
> Thanks your nice work for ERC, a bug from TODKAT was not fixed in your code, see [something678/TodKat#10](https://github.com/something678/TodKat/issues/10). You may need fix it and report the new results.
> 
> Best regards.

Thank you for your feedback, we have fixed this bug and will report new results in the new version.

**Comment by whatissimondoing** [comment]
The new results have been reported in the new version.
