### ISSUE TITLE
询问关于论文中的疑问

### ISSUE THREAD

**Issue by Z-yolo** [whatissimondoing/CoG-BART#2]
作者您好!  我在学习你的论文过程中中有些疑问，在你的论文公式（8）中，你们通过聚合上下文信息使用Dialogue-level Transformer来进行上下文依赖建模，但为什么公式中我们只能看出来你们只用了当前话语 t 的下文，并没与上文的信息哎。
冒昧打扰，希望见谅！

**Comment by whatissimondoing** [comment]
因为输入给Dialogue-level Transformer的每一条样例都是一个conversation（或其片段），所以公式（8）中的 t 可理解为是一个相对的时序概念。比如 t 为conversation中的第一个utterance，则其没有上文。
