### ISSUE TITLE
AttributeError: 'torch.Size' object has no attribute 'shape'

### ISSUE THREAD

**Issue by 1973719588** [whatissimondoing/CoG-BART#3]
您好，请问一下源码在Dailydialog数据集train的时候，会遇到一个问题 AttributeError: 'torch.Size' object has no attribute 'shape'
这里，在做位置编码的时候，您的输入input_shape已经是一个size的属性，不是一个tensor了，不会有shape这个属性，想请问一下哪里不对？
![2c6ad59a4f26d7b6daec8b327a2ffb9](https://user-images.githubusercontent.com/71536740/215665254-2120cbc9-3925-4ba4-9700-44b3bc541deb.png)

![629951730bc8ef6cabb8b109d0f8d3e](https://user-images.githubusercontent.com/71536740/215665331-1e4cf8b4-6c22-4157-a191-a3547bab2537.png)

**Comment by WISH-WEI** [comment]
您好！请问您解决了这个问题嘛？？

**Comment by vvangzhengyang** [comment]
> 您好，请问一下源码在Dailydialog数据集train的时候，会遇到一个问题 AttributeError: 'torch.Size' object has no attribute 'shape' 这里，在做位置编码的时候，您的输入input_shape已经是一个size的属性，不是一个tensor了，不会有shape这个属性，想请问一下哪里不对？ ![2c6ad59a4f26d7b6daec8b327a2ffb9](https://user-images.githubusercontent.com/71536740/215665254-2120cbc9-3925-4ba4-9700-44b3bc541deb.png)
> 
> ![629951730bc8ef6cabb8b109d0f8d3e](https://user-images.githubusercontent.com/71536740/215665331-1e4cf8b4-6c22-4157-a191-a3547bab2537.png)

应该是transformers的版本问题

**Comment by whatissimondoing** [comment]
Yes, please use transformers==4.11.0 as stated in README.
