### ISSUE TITLE
problem about the data file of MELD

### ISSUE THREAD

**Issue by Dengdan-1999** [whatissimondoing/CoG-BART#5]
No such file or directory: './data/MELD/train_data_generation.json'
excuse me, thank you for your wonderful paper, but when I want to running the code on dataset MELD, I have encounted the problem as above. did anyone have the same issue with me? who can give me a hand,please. thank you sooooooo much! it seems like that the file named './data/MELD/train_data_generation.json' does't exist. what the file is ? how can I get it?

**Comment by whatissimondoing** [comment]
Where does this file's code segment appear? If the file 'train_data_generation.json' doesn't exist, you can try creating it yourself - just use each subsequent sentence as the prediction target for the current sentence.

**Comment by Dengdan-1999** [comment]
thank you so much. I just find that I forget to run the data_process.py first! so nice an author you are to give a detail guidence!
